version: "3"

services:
  users-database:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres   
  application-database:
    image: mongo:6.0.3
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  hash-translator:
    build:
      context: hashtranslator-service
    restart: unless-stopped
    ports:
      - "81:8181"
    depends_on:
      - application-database  
  authorization-service:
    build:
      context: authorization-service
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - users-database 